name: tinder_clone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.6
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  firebase_core: ^2.16.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  geolocator: ^12.0.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  persistent_bottom_nav_bar_v2: ^5.3.0
  swipe_cards: ^2.0.0+1
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
